name: jiosaavn
description: JioSaavn extension for Musica app.
version: 1.0.0
environment:
  sdk: '>=2.10.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.10.11
  freezed: ^0.12.6
  json_serializable: ^3.5.1
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  freezed_annotation: ^0.12.0
